version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    # Setzt die Umgebungsvariable für den Host, damit die Vue-App im Container läuft und von außen erreichbar ist
    environment:
      - CHOKIDAR_USEPOLLING=true # Nötig für Hot-Reload unter bestimmten OS/Dateisystemen in Docker