name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main                 # Branch for the Deploy

jobs:                        # jobs aka automations 
  build-and-deploy:          # name of the workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist    # web-optimized and finished app is located in dist
